name: Love actions for Linux
description: Linux CI/CD for LÖVE based games
branding:
  icon: "heart"
  color: "orange"
inputs:
  desktop-file-path:
    description: |
      Path to the desktop file
      Would be used as appImage's info file
    required: false
  executable-name:
    description: |
      Executable name
      Would be used as appImage's internal executable filename
    required: false
    default: "love"
  icon-path:
    description: |
      Path to the icon
      Would be used in building appImage
    required: false
  love-package:
    description: |
      Love package
      Would be used to assemble the executable
    required: false
    default: "./game.love"
  lib-path:
    description: |
      Path to the lib folder
      Would copy all contents to squashfs-root/lib/lua/5.1
      Top folder not included
    required: false
  share-path:
    description: |
      Path to the share folder
      Would copy all contents to squashfs-root/share/lua/5.1
      Top folder not included
    required: false
  product-name:
    description: |
      Base name of the package
      Would be used to rename products
    required: false
    default: "love_app"
  output-folder:
    description: |
      Packages output folder
      All packages would be placed here
    required: false
    default: "./build"
outputs:
  package-paths:
    description: |
      Paths to the built packages in a bash list
      Would be paths relative to repository root, separated by spaces
      Looks like: ./build/game.AppImage
    value: ${{ steps.gather-packages.outputs.package-paths }}
runs:
  using: "composite"
  steps:
    - name: Create directories
      shell: bash
      run: |
        mkdir -p ./love-actions-linux/
        mkdir -p ${{ inputs.output-folder }}
    - name: Install libfuse2
      shell: bash
      run: |
        sudo add-apt-repository universe
        sudo apt install libfuse2
    - name: Download AppImageKit and love appImage
      shell: bash
      run: |
        cd ./love-actions-linux/

        curl -OL --retry 5 https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
        mv ./appimagetool-x86_64.AppImage ./appimagetool.AppImage
        chmod a+x ./appimagetool.AppImage

        curl -OL --retry 5 https://github.com/love2d/love/releases/download/11.4/love-11.4-x86_64.AppImage
        chmod +x ./love-11.4-x86_64.AppImage
        ./love-11.4-x86_64.AppImage --appimage-extract
    - name: Assemble executable
      shell: bash
      run: |
        cat ./love-actions-linux/squashfs-root/bin/love ${{ inputs.love-package }} > ./love-actions-linux/squashfs-root/bin/${{ inputs.executable-name }}
        chmod +x ./love-actions-linux/squashfs-root/bin/${{ inputs.executable-name }}
    - name: Set icon
      if: "${{ inputs.icon-path != '' }}"
      shell: bash
      run: |
        rm -rf ./love-actions-linux/squashfs-root/love.svg ./love-actions-linux/squashfs-root/.DirIcon
        cp ${{ inputs.icon-path }} ./love-actions-linux/squashfs-root/
        mv ${{ inputs.icon-path }} ./love-actions-linux/squashfs-root/.DirIcon
    - name: Set desktop file
      if: "${{ inputs.desktop-file-path != '' }}"
      shell: bash
      run: |
        rm -rf ./love-actions-linux/squashfs-root/love.desktop
        mv ${{ inputs.desktop-file-path }} ./love-actions-linux/squashfs-root/${{ inputs.product-name }}.desktop
    - name: Copy lib
      if: "${{ inputs.lib-path != '' }}"
      shell: bash
      run: |
        mkdir -p ./love-actions-linux/squashfs-root/lib/lua/5.1
        cp -r -f ${{ inputs.lib-path }} ./love-actions-linux/squashfs-root/lib/lua/5.1
    - name: Copy share
      if: "${{ inputs.share-path != '' }}"
      shell: bash
      run: |
        mkdir -p ./love-actions-linux/squashfs-root/usr/share/lua/5.1
        cp -r -f ${{ inputs.share-path }} ./love-actions-linux/squashfs-root/share/lua/5.1
    - name: Pack package
      shell: bash
      run: |
        ./love-actions-linux/appimagetool.AppImage ./love-actions-linux/squashfs-root ${{ inputs.output-folder }}/${{ inputs.product-name }}.AppImage
    - name: Gather packages in output folder
      id: gather-packages
      shell: bash
      run: |
        echo "package-paths=$(ls -d ${{ inputs.output-folder }}/* | tr '\r\n' ' ')" >> $GITHUB_OUTPUT
    - name: Cleanup
      shell: bash
      run: |
        rm -rf ./love-actions-linux/
